index:
    path: /
    controller: App\Controller\SorteoController::index

app_numero_sorteo:
    path: /sorteo/numero
    controller: App\Controller\SorteoController::numero

app_numero_sorteo_max:
    path: /sorteo/numeroMaximo/{maximo}
    controller: App\Controller\SorteoController::numeroMaximo
    defaults:
        maximo: 100 

app_numero_suma:
    path: /sorteo/suma/{numero1}/{numero2}
    controller: App\Controller\SorteoController::numeroSuma
    defaults:
        numero1: 2
        numero2: 2
